### ISSUE TITLE
3.8-13.04 update caused network widget on dashboard to not work

### ISSUE THREAD

**Issue by barnhill** [rockstor/rockstor-core#1302]
Widget used to show network traffic does not work after the 3.8-13.04 upgrade

**Comment by MFlyer** [comment]
Hi @barnhill can you post a screenshot and/or browser console logs??

thanks

**Comment by phillxnet** [comment]
@barnhill Thanks for reporting this; however I think this is a duplicate of #1289 where we already have a little investigation and a more accurate starting point for the occurrence of the issue.
@MFlyer Do you agree? In which case then maybe one or the other should be closed and all info copied into the remaining issue, ie version numbers / findings etc. A small and hopefully relevant console log excerpt is available in the referenced issue.

**Comment by MFlyer** [comment]
Hi @phillxnet , totally agree with you - didn't remember about that issue.

@barnhill can you please close this issue and referer to the other one (as told by @phillxnet on the other side we already have more infos to start with)

Flyer

**Comment by barnhill** [comment]
I had the previous version and it worked just fine.  Any ideas on how that would be possible?

**Comment by phillxnet** [comment]
@barnhill As far as I was aware this network widget broken issue started at 3.8-12.13 hence my suspicion this was a duplicate. Are you saying all was well with your install on 3.8-13.03 (the previous version to 3.8-13.04? When ever you update it will jump to what ever is the newest version in the updates channel you are subscribed to. Could you have jumped a few versions?

I have so far assumed that the widget was broken by #1253 as directly after that pr was when I first noticed this and opened the referenced issue.

**Comment by MFlyer** [comment]
Hi all @phillxnet and @barnhill , done some checking over network widget and found why actually not working:

On #1253 @schakrava added storageadmin.networkconnection over storageadmin.networkdevice (every connection is done over 1 or more devices - teaming/bonding or single device connection, as it was before update), meanwhile network widget still collects initial data from smart_manager_netstat that actually is empty.
Widget view js file has first data grabbing over func `getInitialData` that ask for `/api/sm/sprobes/netstat/?format=json&page_size=1` giving empty results array, so while updating data (every sec) js pushes to dataBuffers being empty/without references for interfaces.

To @schakrava : if you can handle .py side of netstat class i can work on view side :smile: (some errors on getData too -> `this.t2 = new Date(data.results[0].ts)` has to be `this.t2 = new Date(data.results[0]['ts'])` because results returns  an array and each element contains a dictionary, so you have to reference by key)

Flyer

**Comment by MFlyer** [comment]
After some checks, data.results[0].ts get broken because of missing data, but if we fix it that gets ok

@schakrava Looking to this commit -> d3aa68e if we move to `NetworkDeviceCollection` instead of `NetworkConnectionCollection` Network widget works fine (reads data for every device and not for "connection object" that actually i suppose to be a "Rockstor naming convention")

Finally i think it's a big misunderstanding related to names:
My eth0 device is on eth0 connection (but on sys side that is always eth0 device)
Meanwhile a bond0 connection would refer to a bond0 device (made of eth0 and eth1 devices)

**Comment by MFlyer** [comment]
Back again with my Rockstor env up after a stupid test (added ethx with auto without having a nic so got a conflict over eth0 and mess for ips), now we can play (vm snapshot taken!!): @phillxnet as told in PR, do you have 2 avail nics to test if once joined over a team/bond they appear on devices??

My experience: we should have 3 devices (bond0, eth0 slave and eth1 slave, all giving info about current traffic)

**Comment by phillxnet** [comment]
@MFlyer Will have such a setup shortly but as indicated in my comment on the pr it will take a little longer at this end than I would like I'm afraid.

**Comment by MFlyer** [comment]
Hi @phillxnet not a problem, Proxmox allows me to do "stupid things" like having 3 nics with just one nic so I've tested :stuck_out_tongue_closed_eyes:  (eth0 let me be always inside web ui without kicking me out, eth1 and eth2 for bond/team testing)

What I've done (maybe we need to better explain bond/teaming creation):
- add eth1 connection like ethernet
- add eth2 connection like ethernet
- add bond0 connection with members eth1 and eth2 **connections** (not devices, important!)
- Rockstor auto shutdown eth1 and eth2 connections, while waking bond0 (great!! @schakrava :sunglasses:, that's a kind of "protection system" to avoid user kicked out while eths down in favor of bond!)
- Delete eth1 and eth2 connections

As i expected NetworkDeviceCollection works properly and shows us all devices: lo, eth0, bond0, eth1 and eth2, cos bond0 is the master connection, but eth1 and eth2 are still net devices (bond0 data right, differs from eth1 and eth2)

So finally, I think my PR solves it in the right way (if we don't want to show bond/team slaves then we have to code and filter on js side...but actually network widget - my point of view - correctly reflects system data)

**Comment by barnhill** [comment]
This still isnt fixed.  in 3.8-13.11

**Comment by MFlyer** [comment]
Hi @barnhill , you're right saying that hasn't been fixed with 3.8-13.11:
while it seems ok under chrome/chromium, there are some problems over firefox (Check pull requeste last part -> https://github.com/rockstor/rockstor-core/pull/1311#issuecomment-219712705)
Hope to solve asap :blush:

**Comment by barnhill** [comment]
I'm using chrome and its not ok

Brad Barnhill
bradbarnhill@hotmail.com

**Comment by MFlyer** [comment]
> I'm using chrome and its not ok
Brad Barnhill

??? Have you manually changed this -> 	33b2d1a and built static to test??

**Comment by barnhill** [comment]
Nah

Brad Barnhill
bradbarnhill@hotmail.com

**Comment by MFlyer** [comment]
Ok, so you're still running without any patch. Right it's not solved

**Comment by barnhill** [comment]
Right no patch

Brad Barnhill
bradbarnhill@hotmail.com

**Comment by MFlyer** [comment]
To @schakrava : issue to be closed

**Comment by barnhill** [comment]
So it's being closed cause it's fixed?  In the latest 3.8-13.13 its still not working.

**Comment by MFlyer** [comment]
> So it's being closed cause it's fixed? In the latest 3.8-13.13 its still not working

Hi @barnhill , this will be closed because over pull request #1323 got solved (already merged into Rockstor, not available on 3.8-13.13, probably on next release :smiley: )

**Comment by barnhill** [comment]
Oh okay ... sounds good!!  Thanks for getting it fixed.

Brad Barnhill
bradbarnhill@hotmail.com

**Comment by MFlyer** [comment]
Hi @barnhill , now on 3.8-13.14 issue has been fixed :smile: 

Flyer

P.S.: @schakrava or @barnhill - Issue to be closed

**Comment by barnhill** [comment]
Just updated to 3.8-13.18 and now its fixed.  As of 17 it was still broken but 18 fixed it on my machine.  Thanks.
